#!/bin/sh -e

# automatic build maker

#build version

echo "Starting `basename "$0"`" >> ./build-log

END=$1

BASE="openwrt-"
BASEO="openwrt-ar71xx-generic-tl-"
BASEQ="openwrt-ar71xx-generic-"
ENDO="-squashfs-factory"
ENDU="-squashfs-sysupgrade"

echo "                            <model>" > ./files/etc/header_msg
echo "/img/rooter.png" >> ./files/etc/header_msg
echo "/img/rooter.png" >> ./files/etc/header_msg

cp ./configfiles/.config_300nv2 ./.config
make V=s

# MT300N-v2

MOD="mt300n-v2"
EXTB=".bin"

ORIG=openwrt-ramips-mt76x8-gl-mt300n-v2-squashfs-sysupgrade.bin
FIRM=$BASE$MOD$END"-upgrade"$EXTB
cp ./bin/targets/ramips/mt76x8/$ORIG ./images/$FIRM
cd ./images
zip $MOD$END.zip $FIRM
rm -f $FIRM
cd ..

echo "     Ending `basename "$0"`" >> ./build-log
