#!/bin/sh -e

# automatic build maker

#build version

echo "Starting `basename "$0"`" >> ./build-log

END=$1

BASE="openwrt-"
BASEO="openwrt-ar71xx-generic-tl-"
BASEQ="openwrt-ar71xx-generic-"
ENDO="-squashfs-factory"
ENDU="-squashfs-sysupgrade"

cp ./configfiles/.config_826 ./.config
make V=s

# WE826/WE1026

MOD="we826"
EXTB=".bin"

ORIG=openwrt-ramips-mt7620-zbt-we826-16M-squashfs-sysupgrade.bin
FIRM=$BASE$MOD$END-upgrade$EXTB
cp ./bin/targets/ramips/mt7620/$ORIG ./images/$FIRM
cd ./images
zip $MOD$END.zip $FIRM
rm -f $FIRM
cd ..

echo "     Ending `basename "$0"`" >> ./build-log
