#!/bin/sh

# automatic build maker

#build version

END=$1

BASE="openwrt-"
BASEO="openwrt-ar71xx-generic-tl-"
BASEQ="openwrt-ar71xx-generic-"
ENDO="-squashfs-factory"
ENDU="-squashfs-sysupgrade"

cp ./configfiles/.config_b1300 ./.config
make V=s

# gl1300

MOD="GL-B1300"
EXTB=".bin"

ORIG=openwrt-ipq40xx-glinet_gl-b1300-squashfs-sysupgrade.bin
FIRM="openwrt-"$MOD$END-upgrade$EXTB
FIRM1="lede-gl-b1300.bin"
cp ./bin/targets/ipq40xx/generic/$ORIG ./images/$FIRM
cp ./bin/targets/ipq40xx/generic/$ORIG ./images/$FIRM1
cp ./configfiles/GL/readme.txt ./images/readme.txt
cd ./images
zip $MOD$END.zip $FIRM $FIRM1 readme.txt
rm -f $FIRM
rm -f $FIRM1
rm -f readme.txt
cd ..


