#!/bin/sh -e

# automatic build maker

#build version

echo "Starting `basename "$0"`" >> ./build-log

END=$1

BASE="openwrt-"
BASEO="openwrt-ar71xx-generic-tl-"
BASEQ="openwrt-ar71xx-generic-"
ENDO="-squashfs-factory"
ENDU="-squashfs-sysupgrade"

cp ./configfiles/.config_mifi ./.config
make V=s

MOD="gl-mifi"
EXTB=".bin"

ORIG=$BASEQ$MOD$ENDU$EXTB
FIRM=$BASE$MOD$END-upgrade$EXTB
cp ./bin/targets/ar71xx/generic/$ORIG ./images/$FIRM
cp ./configfiles/GL/readme.txt ./images/readme.txt
cd ./images
zip $MOD$END.zip $FIRM readme.txt
rm -f $FIRM
rm -f readme.txt
cd ..

echo "     Ending `basename "$0"`" >> ./build-log
